//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
//using UnityEngine.Random;
using System.Collections;

public class RandChoices : MonoBehaviour {
	int maxSize = 0;
	float timer = 0;
	Random rand = new Random();
	int choiceIndex = 0;
	bool useWheel = true;
	bool timerFinished = false;
	string currentChoice = "";
	string[] hiddenChoices;
	string[] choices;
	private int groupWidth = 200;
	private int groupHeight = 170;
	void Update(){
		if (useWheel) {
			if (!Camera.main.GetComponent<AudioSource> ().isPlaying) {
				useWheel = false;
			} 
		} else {
			if(!timerFinished)
				timer += Time.deltaTime;
		}
	}
	void Start ()
	{
		choices = new string[5]{"???????", "???????","???????","???????","???????"};
		hiddenChoices = new string[5]{"This is It", "N", "A", "b", "c"};
		maxSize = hiddenChoices.Length;
		choiceIndex = Random.Range (0, maxSize);
	}
	void Awake(){
		choiceIndex = Random.Range(0, maxSize);
		useWheel = true;
		timer = 0;
	}
	public string GetRandomChoice ()
	{
		changeChoices ();
		return hiddenChoices [choiceIndex];
	}
	public void changeChoices ()
	{
		currentChoice= hiddenChoices [choiceIndex];
		choices [choiceIndex] = currentChoice;
	}
	bool TogglePause()
	{
		if (Time.timeScale == 0) {
			Time.timeScale = 1;
			return(false);
		} else {
			Time.timeScale = 0;
			return(true);
		}
	}
	void OnGUI () {
		if (timer < 5) {
			GUI.color = Color.white;
			GUI.BeginGroup (new Rect (((Screen.width / 2) - (groupWidth / 2)), ((Screen.height / 2) - (groupHeight / 2)), groupWidth, groupHeight));
			for(int i= 0, j = 0; i < maxSize; i++, j += 20 ){
				GUI.color = Color.white;
				GUI.TextArea (new Rect (0, 0 + j, 100, 20), choices[i]);
			}
			GUI.EndGroup ();
		} 
		else if (timer >= 5){
			string eventChosen = GetRandomChoice();
			for(int i= 0, j = 0; i < maxSize; i++, j += 20 ){
				if(eventChosen.CompareTo(choices[i]) != 0){
					GUI.color = Color.white;
					GUI.TextArea (new Rect (0, 0 + j, 100, 20), choices[i]);
				}else{
				    GUI.color = Color.yellow;
					GUI.TextArea (new Rect (0, 0 + j, 100, 20), choices[i]);
				}
			}
			timerFinished = true;
		}
	}
}

