//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
//using UnityEngine.Random;
using System.Collections;

public class RandChoices : MonoBehaviour {
	int maxSize = 0;
	int choiceIndex = 0;
	string currentChoice = "";
	string[] hiddenChoices = {"This is It", "N", "A", "b", "c"};
	string[] choices = {"???????", "???????","???????","???????","???????"};


	public RandChoices ()
	{
		choiceIndex = 0;
		maxSize = hiddenChoices.Length;
	}
	public string GetRandomChoice ()
	{
		Random rand = new Random();
		//choiceIndex = rand.Range(0f, (float)maxSize);
		changeChoices ();
		return hiddenChoices [choiceIndex];
	}
	public void changeChoices ()
	{
		currentChoice= hiddenChoices [choiceIndex];
		choices [choiceIndex] = currentChoice;
	}
}

